package aula2_2024;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

public class AcerteAlvo extends javax.swing.JFrame {

    /**
     * Creates new form AcerteAlvo
     */
    public AcerteAlvo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jImagem = new javax.swing.JLabel();
        la = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acerte o Alvo");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(640, 440));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aula2_2024/img/ALVO.png"))); // NOI18N
        jImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jImagemMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jImagemMouseExited(evt);
            }
        });
        getContentPane().add(jImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 200, 170));

        la.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        la.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        la.setText("ACERTOS: ");
        getContentPane().add(la, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 200, -1));

        setSize(new java.awt.Dimension(616, 445));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImagemMouseClicked
        
        mudar("img/ALVO2.png");
        acerto ++;
        
        la.setText("ACERTOS: " + acerto);
          
    }//GEN-LAST:event_jImagemMouseClicked

    private void jImagemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImagemMouseExited
        
        mudar("img/ALVO.png");
        
        
    }//GEN-LAST:event_jImagemMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       cordenadas.start();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcerteAlvo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcerteAlvo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcerteAlvo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcerteAlvo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcerteAlvo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jImagem;
    private javax.swing.JLabel la;
    // End of variables declaration//GEN-END:variables

    //variaveis globais
    int x;
    int y;
    int cont = 0, acerto = 0;
    
    public void mudar(String end){
        Image troca = Toolkit.getDefaultToolkit().getImage(getClass().getResource(end));
        
        ImageIcon icone = new ImageIcon(troca);
        
        jImagem.setIcon(icone);
        
    }
    
    private javax.swing.Timer cordenadas = new javax.swing.Timer(600, new java.awt.event.ActionListener() { 
              public void actionPerformed(java.awt.event.ActionEvent e) {

                  x = 1 + (int) (600 * Math.random());
                  y = 1 + (int) (400 * Math.random());
                  
                  jImagem.setLocation(x,y);
                     
   }//fim do evento
});//fim método timer

}//NAO APAGAR
